#!/usr/bin/env bash
# __     _______
# \ \   / /_   _|  Vox Tetra
#  \ \ / /  | |    https://www.github.com/VoxT1
#   \ V /   | |    https://www.twitter.com/VoxTetra1
#    \_/    |_|    vt#9827
#
# My Herbstluftwm configuration.
#
#### AUTOSTART ####
hc() {
    herbstclient "$@"
}
hc emit_hook reload
xsetroot -solid '#5A8E3A'

## Monitors ##
if [[ $(xrandr -q | grep 'DP-2 connected') ]]; then
       xrandr --output DP-2 --mode 2560x1440 --rate 165 --pos 440x0 --output DP-0 --mode 3440x1440 --rate 144 --pos 0x1440 &
else
       xrandr --output DP-0 --mode 3440x1440 --rate 144 &
fi

## Clipmenu ##
clipmenud &

## Compositor ##
picom --experimental-backend &

## Wallpaper ##
nitrogen --restore &

#### KEYBINDS ####
## Remove existing keybinds ## 
hc keyunbind --all

### MOD KEY ###
## Alt ##
Mod=Mod1

## Super ##
# Mod=Mod4   

### SESSION ###
## Exit Herbstluftwm ##
hc keybind Super-Shift-Escape quit

## Reload Herbstluftwm ##
hc keybind Super-Shift-r reload

## Close program ##
hc keybind $Mod-q close

## Lock screen ##
hc keybind Super-Escape spawn i3lock -c 2B3143

## Launch terminal ##
hc keybind $Mod-Control-z spawn alacritty 


### PROGRAMS ###
## Keybinds to launch specific programs ##
hc keybind $Mod-w spawn librewolf
hc keybind $Mod-Shift-w spawn firefox-bin
hc keybind $Mod-l spawn lowriter 
hc keybind $Mod-space spawn dmenu_run 
hc keybind $Mod-e spawn thunar
hc keybind $Mod-d spawn discord
hc keybind $Mod-Shift-d spawn deadbeef
hc keybind $Mod-g spawn steam
hc keybind $Mod-s spawn spotify
hc keybind $Mod-Shift-p spawn pavucontrol
hc keybind $Mod-v spawn clipmenu 
hc keybind $Mod-p spawn flameshot gui
hc keybind $Mod-Shift-w spawn nitrogen
hc keybind $Mod-m spawn multimc-bin

### VOLUME ###
## Volume Up ##
hc keybind $Mod-period spawn pactl set-sink-volume @DEFAULT_SINK@ +5%
hc keybind $Mod-Shift-period spawn pactl set-sink-volume @DEFAULT_SINK@ +10%

## Volume Down ##
hc keybind $Mod-comma spawn pactl set-sink-volume @DEFAULT_SINK@ -5%
hc keybind $Mod-Shift-comma spawn pactl set-sink-volume @DEFAULT_SINK@ -10%

## Mute ##
hc keybind $Mod-apostrophe spawn pactl set-sink-mute @DEFAULT_SINK@ toggle

### FOCUS ###
hc keybind Super-h	focus left
hc keybind Super-j	focus down
hc keybind Super-k	focus up
hc keybind Super-l	focus right

#hc keybind Super-d     focus left
#hc keybind Super-h     focus down
#hc keybind Super-t     focus up
#hc keybind Super-n     focus right

### MOVEMENT ###
hc keybind Super-Shift-h	shift left
hc keybind Super-Shift-j	shift down
hc keybind Super-Shift-k	shift up
hc keybind Super-Shift-l	shift right

#hc keybind Super-Shift-d     shift left
#hc keybind Super-Shift-h     shift down
#hc keybind Super-Shift-t     shift up
#hc keybind Super-Shift-n     shift right

### SPLITTING FRAMES ###
## Creates a new frame in the specified direction ##
hc keybind Super-minus       split   bottom  0.5
hc keybind Super-equal       split   right   0.5

hc keybind Super-Control-space split explode

### RESIZING FRAMES ### 
## Amount by which the frame is resized ##
resizestep=0.02
hc keybind Super-Control-h       resize left +$resizestep
hc keybind Super-Control-j       resize down +$resizestep
hc keybind Super-Control-k       resize up +$resizestep
hc keybind Super-Control-l       resize right +$resizestep

#hc keybind Super-Control-d       resize left +$resizestep
#hc keybind Super-Control-h       resize down +$resizestep
#hc keybind Super-Control-t       resize up +$resizestep
#hc keybind Super-Control-n       resize right +$resizestep

### TAGS ###
tag_names=( {1..6} )
tag_keys=( {1..6} 0 )

hc rename default "${tag_names[0]}" || true
for i in "${!tag_names[@]}" ; do
    hc add "${tag_names[$i]}"
    key="${tag_keys[$i]}"
    if ! [ -z "$key" ] ; then
        hc keybind "$Mod-$key" use_index "$i"
        hc keybind "$Mod-Shift-$key" move_index "$i"
    fi
done

## CYCLE TAGS ##
hc keybind $Mod-Right use_index +1 --skip-visible
hc keybind $Mod-Left  use_index -1 --skip-visible

### LAYOUTS ###
## Remove selected frame ##
hc keybind Super-q remove

## Toggle floating for frame ##
hc keybind Super-f floating toggle

## Toggle fullscreen ##
hc keybind Super-Control-f fullscreen toggle

## Toggle floating for selected program ##
hc keybind Super-Shift-f set_attr clients.focus.floating toggle

## Minimize ##
hc keybind Super-Shift-m set_attr clients.focus.minimized true

## Open minimized ##
hc keybind Super-Control-m jumpto last-minimized

## Toggle pseudotile ##
hc keybind Super-p pseudotile toggle

## Cycles through layouts ##
hc keybind Super-space                                                           \
            or , and . compare tags.focus.curframe_wcount = 2                   \
                     . cycle_layout 1 grid horizontal vertical\
               , cycle_layout -1

### MOUSE ###
hc mouseunbind --all
hc mousebind Super-Button1 move
hc mousebind Super-Button2 zoom
hc mousebind Super-Button3 resize

### FOCUS ###
hc keybind $Mod-BackSpace   cycle_monitor
hc keybind $Mod-Tab         cycle_all +1
hc keybind $Mod-Shift-Tab   cycle_all -1
hc keybind $Mod-c cycle
hc keybind $Mod-i jumpto urgent

#### THEMES/APPEARANCE ####
hc attr theme.tiling.reset 1
hc attr theme.floating.reset 1
hc set frame_border_active_color '#222222cc'
hc set frame_border_normal_color '#101010cc'
hc set frame_bg_normal_color '#6E4A5Faa'
hc set frame_bg_active_color '#FF79C6aa'
hc set frame_border_width 2
hc set always_show_frame off
hc set frame_bg_transparent on
hc set frame_transparent_width 2
hc set frame_gap 0

hc attr theme.title_height 0
hc attr theme.title_font 'terminus:pixelsize=12'
# hc attr theme.title_font '-*-fixed-medium-r-*-*-13-*-*-*-*-*-*-*'
hc attr theme.padding_top 0
hc attr theme.active.color '#BD93F9'
hc attr theme.title_color '#ffffff'
hc attr theme.normal.color '#523E6Fdd'
hc attr theme.urgent.color '#7811A1dd'
hc attr theme.normal.title_color '#898989'
hc attr theme.inner_width 0
hc attr theme.inner_color black
hc attr theme.border_width 2
hc attr theme.floating.border_width 2
hc attr theme.floating.outer_width 0
hc attr theme.floating.outer_color black
hc attr theme.active.inner_color '#789161'
hc attr theme.urgent.inner_color '#9A65B0'
hc attr theme.normal.inner_color '#606060'

# copy inner color to outer_color
for state in active urgent normal ; do
    hc substitute C theme.${state}.inner_color \
        attr theme.${state}.outer_color C
done
hc attr theme.active.outer_width 1
hc attr theme.background_color '#141414'

hc set window_gap 10
hc set frame_padding 0
hc set smart_window_surroundings off
hc set smart_frame_surroundings on
hc set mouse_recenter_gap 0

#### RULES ####
hc unrule -F

## Specific program rules ##
hc rule class=Pavucontrol floating=on
hc rule class=Deadbeef floating=on
hc rule class=Gcolor2 floating=on

## Focus new clients ##
hc rule focus=on 

## Floating windows placement ##
hc rule floatplacement=center

hc rule windowtype~'_NET_WM_WINDOW_TYPE_(DIALOG|UTILITY|SPLASH)' floating=on
hc rule windowtype='_NET_WM_WINDOW_TYPE_DIALOG' focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(NOTIFICATION|DOCK|DESKTOP)' manage=off

hc set tree_style '╾│ ├└╼─┐'

#### FINISHING UP ####
hc unlock
hc detect_monitors
hc set focus_follows_mouse true
hc set_layout grid 

## Panel shit ##
panel=~/.config/polybar/launch.sh
#[ -x "$panel" ] || panel=/etc/xdg/herbstluftwm/panel.sh
#for monitor in $(hc list_monitors | cut -d: -f1) ; do
#    # start it on each monitor
#    "$panel" "$monitor" &
#done
