#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

xrandr --output DP-1 --mode 3440x1440 --rate 144 --pos 0x1440 --output DP-2 --mode 3440x1440 --rate 144 --pos 1720x0 &
sxhkd &
nitrogen --restore &
picom --experimental-backend &
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
./.config/bspwm/launch.sh &

bspc monitor DP-1 -d 1 2
bspc monitor DP-2 -d 3 4

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true

bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action2 resize_corner

bspc rule -a Gimp state=floating center=on
bspc rule -a MultiMC state=floating center=on
bspc rule -a Leafpad state=floating
bspc rule -a Thunar state=floating center=on
bspc rule -a Emacs state=tiled
