#!/usr/bin/env bash
# __     _______
# \ \   / /_   _|  Vox Tetra
#  \ \ / /  | |	   https://www.github.com/VoxT1
#   \ V /   | |    https://www.twitter.com/VoxTetra1
#    \_/    |_|    vt#9827
#
# My Bspwm configuration.
#
### AUTOSTART ###
sxhkd &
picom --experimental-backend &
#$HOME/.config/polybar/launch.sh
nitrogen --restore &
clipmenud &

### CURSOR ###
xsetroot -cursor_name left_ptr 

### MONITORS ###

## 3440 on top, 2560 on bottom
#if [[ $(xrandr -q | grep 'DP-2 connected') ]]; then
#	xrandr --output DP-2 --mode 2560x1440 --rate 165 --pos 440x1440 --output DP-0 --mode 3440x1440 --rate 144 & 
#else
#	xrandr --output DP-0 mode 3440x1440 --rate 144 &
#fi

## 3440 on bottom, 2560 on top
if [[ $(xrandr -q | grep 'DP-2 connected') ]]; then
	xrandr --output DP-2 --mode 2560x1440 --rate 165 --pos 440x0 --output DP-0 --mode 3440x1440 --rate 144 --pos 0x1440 &
else
	xrandr --output DP-0 --mode 3440x1440 --rate 144 &
fi

## workspaces ##
bspc monitor DP-0 -d 1 2 3 4 5 6 7 8
bspc monitor DP-2 -d 1 2 3 4 5 6 7 8

### COLORS ###
## GRUVBOX ##
#bspc config normal_border_color	"#55541D"
#bspc config focused_border_color	"#98971A"

## DRACULA ##
bspc config normal_border_color		"#4D415D"
bspc config focused_border_color	"#BD93F9"

### BORDERS ###
bspc config border_width	2
bspc config window_gap		10 

### RULES ###
bspc rule -a Deadbeef state=floating
bspc rule -a Nitrogen state=floating
bspc rule -a Galculator state=floating
bspc rule -a mpv state=floating
bspc rule -a Pavucontrol state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

### OTHER SHIT ###
pgrep -x sxhkd > /dev/null || sxhkd &

bspc config split_ratio		0.50

bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner

bspc config focus_follows_pointer true
bspc config borderless_monocle   true
bspc config gapless_monocle      true
