#!/usr/bin/env bash
# __     _______
# \ \   / /_   _|  Vox Tetra
#  \ \ / /  | |    https://www.github.com/VoxT1
#   \ V /   | |    https://www.twitter.com/VoxTetra1
#    \_/    |_|    vt#9827
#
# A script to list simple power options.

## Define actions
POWEROFF="alacritty -e doas poweroff"
REBOOT="alacritty -e doas reboot"
LOGOUT="kill -9 -1"

## Define the array
declare -a options=(
"Poweroff"
"Reboot"
"Log Out"
)

## Pipe array into dmenu
choice=$(printf '%s\n' "${options[@]}" | dmenu -i -l 20 -p 'System will:')

## User choices
if [[ "$choice" == "Poweroff" ]]; then
	$POWEROFF
elif [ "$choice" == "Reboot" ]; then
	$REBOOT
elif [ "$choice" == "Log Out" ]; then
	$LOGOUT
else
	echo "Program Terminated." && exit 1
fi
